[versions]
agp = "8.6.1"

androidx-core = "1.13.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
fragment = "1.8.4"
recyclerview = "1.3.2"
constraintlayout = "2.1.4"

play-services-location = "21.3.0"

retrofit = "2.11.0"
okhttp = "4.12.0"

glide = "4.16.0"

junit = "4.13.2"
androidx-junit = "1.2.1"
espresso-core = "3.6.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }


[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }

play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

junit = { module = "junit:junit", version.ref = "junit" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
